name: my_trading_bot_app
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=3.6.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  intl: ^0.20.1
  cupertino_icons: ^1.0.8
  http: any
  bip39: ^1.0.0 # برای تولید عبارت بازیابی
  web3dart: ^2.6.4 # برای کار با بلاک‌چین اتریوم
  provider: ^6.0.5 # برای مدیریت وضعیت
  shared_preferences: ^2.1.1 # برای ذخیره‌سازی داده‌های محلی
  flutter_secure_storage: ^9.2.4
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  # بخش مربوط به اضافه کردن دارایی‌های پروژه
  assets:
    
